version: '3.8'

services:
  db:
    build: .
    container_name: ventasdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ventasdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
